from typing import Type, Iterable, Sized, Iterator, NewType

"""
The type which generated by 
google.protobuf.reflection.GeneratedProtocolMessageType
"""
GeneratedProtocolMessageType = "GeneratedProtocolMessageType"


class ProtoList(Sized, Iterable):

    def __init__(self, path, proto_class: Type[GeneratedProtocolMessageType]):
        self.path = path
        self.proto_class = proto_class

    def __enter__(self):
        self.file = open(self.path, 'rb')

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.file.__exit__(exc_type, exc_val, exc_tb)

    def __len__(self) -> int:
        # we do not want to load all messages in memory
        n_of_msgs = 0
        for _ in self.file.readline():
            n_of_msgs += 1
        return n_of_msgs

    def __getitem__(self, item) -> Type[GeneratedProtocolMessageType]:
        self.file.seek(0)
        for _ in range(item):
            self.__iter__()
        return self.__iter__()

    def __iter__(self) -> Iterator[GeneratedProtocolMessageType]:
        # Reference:
        # https://googleapis.dev/python/protobuf/latest/google/protobuf/reflection.html
        n = int.from_bytes(self.file.read(8), 'big')
        proto_message = self.file.read(n)
        yield self.proto_class('_message', proto_message)
